---
abstract: 'Module contaning danish zipcodes for validation and deployment'
author:
  - 'Jonas B. Nielsen, (jonasbn) <jonasbn@cpan.org>'
build_requires:
  Data::Dumper: 0
  Data::FormValidator: 0
  English: 0
  Env: 0
  File::Spec: 0
  Test::Class: 0
  Test::Exception: 0
  Test::Kwalitee: 0
  Test::More: 0
  Test::Perl::Critic: 0
  Test::Prereq::Build: 0
  Test::Taint: 0
configure_requires:
  Module::Build: 0.40
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.112150'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Business-DK-Postalcode
provides:
  Business::DK::Postalcode:
    file: lib/Business/DK/Postalcode.pm
    version: 0.03
  Data::FormValidator::Constraints::Business::DK::Postalcode:
    file: lib/Data/FormValidator/Constraints/Business/DK/Postalcode.pm
    version: 0.01
requires:
  Carp: 0
  Exporter: 0
  Params::Validate: 0
  Scalar::Util: 0
  Tree::Simple: 0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Business-DK-Postalcode
  homepage: http://logicLAB.jira.com/browse/BDKPST
  license: http://www.perlfoundation.org/artistic_license_2_0
  repository: http://logicLAB.jira.com/svn/BDKPST
  x_ProjectChangelog: http://logiclab.jira.com/browse/BDKPST#selectedTab=com.atlassian.jira.plugin.system.project%3Achangelog-panel
  x_ProjectSite: http://logicLAB.jira.com/browse/BDKPST
  x_ProjectWiki: http://logiclab.jira.com/wiki/display/BDKPST/Home
version: 0.03
