---
abstract: 'Module contaning danish zipcodes for validation and deployment'
author:
  - 'Jonas B. Nielsen, (jonasbn) <jonasbn@cpan.org>'
build_requires:
  Data::Dumper: '0'
  Data::FormValidator: '0'
  English: '0'
  Env: '0'
  File::Spec: '0'
  Test::CPAN::Changes: '0'
  Test::Class: '0'
  Test::Exception: '0'
  Test::Kwalitee: '0'
  Test::More: '0'
  Test::Perl::Critic: '0'
  Test::Prereq::Build: '0'
  Test::Taint: '0'
configure_requires:
  Module::Build: '0.42'
dynamic_config: 1
generated_by: 'Module::Build version 0.4205, CPAN::Meta::Converter version 2.142060'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Business-DK-Postalcode
provides:
  Business::DK::Postalcode:
    file: lib/Business/DK/Postalcode.pm
    version: '0.09'
  Data::FormValidator::Constraints::Business::DK::Postalcode:
    file: lib/Data/FormValidator/Constraints/Business/DK/Postalcode.pm
    version: '0.09'
requires:
  Carp: '0'
  Exporter: '0'
  Params::Validate: '0'
  Scalar::Util: '0'
  Tree::Simple: '0'
  perl: v5.10.0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Business-DK-Postalcode
  homepage: http://logicLAB.jira.com/browse/BDKPST
  license: http://www.perlfoundation.org/artistic_license_2_0
  projectChangelog: http://logiclab.jira.com/browse/BDKPST#selectedTab=com.atlassian.jira.plugin.system.project%3Achangelog-panel
  projectSite: http://logicLAB.jira.com/browse/BDKPST
  projectWiki: http://logiclab.jira.com/wiki/display/BDKPST/Home
  repository: https://github.com/jonasbn/bdkpst
version: '0.09'
